permalink:        pretty
markdown:         rdiscount
title:            I found this helped
description:      Unscientific anecdotes about chronic pain
url:              http://ifoundthishelped.com
auto:             true
disqus_shortname: ifth